apiVersion: v1
kind: Pod
metadata:
  name: tmp-shell
  annotations:
    linkerd.io/inject: disabled
spec:
  containers:
    - name: tmp-shell
      image: nicolaka/netshoot
      command: ["/bin/bash"]
      stdin: true
      tty: true
